/*
 * main implementation: use this 'C' sample to create your own application
 *
 */


#include "S32K144.h" /* include peripheral declarations S32K144 */

int main(void)
{
       PCC->PCCn[PCC_PORTD_INDEX]=0x40000000; //HABILITADOR CGC DEL PUERTO D PARA HABILITAR LA INTERFAZ DEL PUERTO D, 1<<30 PAG 633. DEL MANUAL
       PORTD->PCR[0]=0x00000100;//CONFIGURAR EL PIN PTD0 COMO GPIO DENTRO DEL MUX PAGINA 198 DEL MANUAL. 1<<8, SE PUEDE PONER EN BINARIO TAMBIEN
       PTD->PDDR=1;//CONFIGURAR PTD0 COMO SALIDA, PTD0 ES EL LED AZUL, PAGINA 213 DEL MANUAL

      //ESTE CÓDIGO SIGNIFICA QUE AL TENER INSTRUCCIONES DENTRO DEL FOR INFINITO SE LE CONOCE COMO POLLING, LUEGO NO VAN A ESTAR ESAS
       //INSTRUCCIONES YA CUANDO SE VEAN LAS INTERRUPCIONES
        for(;;) {
        	PTD->PDOR=0; //SIRVE PARA ESCRIBIR UN 0 EN LOS 32 bits del puerto D, AUNQUE SOLO SE ESTA USANDO EL BIT 0 PTD0. ESTO VA A
        	//PROVOCAR QUE SE PRENDA EL LED YA QUE CON 0 SE PRENDE DEBIDO AL HARDWARE DE COMO ESTA CONECTADO FISICAMENTE.
        	PTD->PDOR=1;//SIRVE PARA ESCRIBIR UN 1 EN LA POSICION 0 DE LOS 32 bits del puerto D, AUNQUE SOLO SE ESTA USANDO EL BIT 0 PTD0.
        	//ESTO VA A PROVOCAR QUE SE APAGUE EL LED YA QUE CON 1 SE APAGA DEBIDO AL HARDWARE DE COMO ESTA CONECTADO FISICAMENTE.

        }


	return 0;
}
